docker_builder:
  name: cosa
  clone_script:
    - git clone "{{ OPENSHIFT_BUILD_SOURCE }}" .
    - git reset --hard "{{ OPENSHIFT_BUILD_REFERENCE }}"
    - git submodule update --init
  environment:
    QUAY_PASSWORD: ENCRYPTED[893a7ca91bc3e9df46dc764308f12b7f2ec8215577beac6b90430309b1d54624f5cb6c752af5947d91ba449fe3c33fe6]
  build_script: docker build --tag quay.io/vrutkovs/okd-os:builder-$CIRRUS_BUILD_ID . -f Dockerfile.cosa
  login_script: echo ${QUAY_PASSWORD} | docker login quay.io --username "vrutkovs+cirrus" --password-stdin
  push_script: docker push quay.io/vrutkovs/okd-os:builder-$CIRRUS_BUILD_ID

build_task:
  depends_on:
    - cosa
  container:
    image: quay.io/vrutkovs/okd-os:builder-$CIRRUS_BUILD_ID
    kvm: true
  environment:
    QUAY_PASSWORD: ENCRYPTED[893a7ca91bc3e9df46dc764308f12b7f2ec8215577beac6b90430309b1d54624f5cb6c752af5947d91ba449fe3c33fe6]
  test_script: /src/entrypoint.sh