apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-okd-master-disable-mitigations
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
        - contents:
            source: >-
              data:text/plain;charset=utf-8;base64,REVMRVRFIG1pdGlnYXRpb25zPWF1dG8sbm9zbXQKREVMRVRFIHN5c3RlbWQudW5pZmllZF9jZ3JvdXBfaGllcmFyY2h5PTAKQUREIGNncm91cF9ub192MT0iYWxsIgpBREQgcHNpPTEK
            verification: {}
          group: {}
          mode: 384
          overwrite: true
          path: /etc/pivot/kernel-args
          user:
            name: root
